import { Bus, ShiftConfig, ShiftTimeOfDay, PassengerArchetype, LagosDestination } from '../types/game';

export const BUS_PRESETS: Record<string, Bus> = {
  RUSTIC_VAN: {
    id: 'RUSTIC_VAN',
    name: 'Rustic Danfo Van',
    slogan: 'No King as God',
    speed: 0,
    maxSpeed: 85,
    acceleration: 18,
    handling: 0.65,
    heat: 10,
    maxHeat: 100,
    heatDissipationRate: 4.5,
    brakeHealth: 100,
    durability: 100,
    maxDurability: 100,
    capacity: 14,
    passengers: [],
    upgrades: {
      dualRadiatorFan: false,
      heavyBullBar: false,
      roofMegaSpeakers: false,
      musicalHorn: false,
      offroadSuspension: false,
      customUnderglow: false,
    },
    soundSystemVolume: 40,
    fuelPercent: 85,
    comfortMeter: 100,
    turnSignal: 'OFF',
    hazardLights: false,
    wipersActive: false,
    isEngineRunning: true,
    doorState: 'CLOSED',
  },
  TURBO_SPRINTER: {
    id: 'TURBO_SPRINTER',
    name: 'Turbo Sprinter Express',
    slogan: 'Work and Pray',
    speed: 0,
    maxSpeed: 110,
    acceleration: 26,
    handling: 0.8,
    heat: 15,
    maxHeat: 100,
    heatDissipationRate: 6.0,
    brakeHealth: 100,
    durability: 85,
    maxDurability: 85,
    capacity: 18,
    passengers: [],
    upgrades: {
      dualRadiatorFan: true,
      heavyBullBar: false,
      roofMegaSpeakers: true,
      musicalHorn: false,
      offroadSuspension: false,
      customUnderglow: false,
    },
    soundSystemVolume: 65,
    fuelPercent: 75,
    comfortMeter: 100,
    turnSignal: 'OFF',
    hazardLights: false,
    wipersActive: false,
    isEngineRunning: true,
    doorState: 'CLOSED',
  },
  HIGH_RISER_COASTER: {
    id: 'HIGH_RISER_COASTER',
    name: 'High-Riser Coaster Heavy',
    slogan: 'Face Your Front',
    speed: 0,
    maxSpeed: 75,
    acceleration: 14,
    handling: 0.5,
    heat: 12,
    maxHeat: 100,
    heatDissipationRate: 5.0,
    brakeHealth: 100,
    durability: 140,
    maxDurability: 140,
    capacity: 24,
    passengers: [],
    upgrades: {
      dualRadiatorFan: true,
      heavyBullBar: true,
      roofMegaSpeakers: true,
      musicalHorn: true,
      offroadSuspension: true,
      customUnderglow: true,
    },
    soundSystemVolume: 50,
    fuelPercent: 95,
    comfortMeter: 100,
    turnSignal: 'OFF',
    hazardLights: false,
    wipersActive: false,
    isEngineRunning: true,
    doorState: 'CLOSED',
  },

  KEKE_NAPEP: {
    speed: 0,
    maxSpeed: 100,
    acceleration: 5,
    handling: 5,
    durability: 100,
    capacity: 14,
    condition: 100,
    mileage: 0,
    color: '#ffcc00',
    id: 'KEKE_NAPEP',
    name: 'Keke Maruwa',
    slogan: 'God Dey',
    heat: 30,
    fuelPercent: 100,
    doorState: 'CLOSED',
    passengers: [],
    upgrades: {
      loudHorn: false,
      musicalHorn: false,
      ledLights: false,
      leatherSeats: false,
      soundSystem: false,
      engineTuning: false,
      tintedWindows: false,
      alloys: false
    }
  },
  HONDA_CIVIC: {
    speed: 0,
    maxSpeed: 100,
    acceleration: 5,
    handling: 5,
    durability: 100,
    capacity: 14,
    condition: 100,
    mileage: 0,
    color: '#ffcc00',
    id: 'HONDA_CIVIC',
    name: 'Honda Civic EG6',
    slogan: 'VTEC Kicked In',
    heat: 15,
    fuelPercent: 100,
    doorState: 'CLOSED',
    passengers: [],
    upgrades: {
      loudHorn: false,
      musicalHorn: false,
      ledLights: false,
      leatherSeats: false,
      soundSystem: false,
      engineTuning: false,
      tintedWindows: false,
      alloys: false
    }
  },
  POLICE_CAR: {
    speed: 0,
    maxSpeed: 100,
    acceleration: 5,
    handling: 5,
    durability: 100,
    capacity: 14,
    condition: 100,
    mileage: 0,
    color: '#ffcc00',
    id: 'POLICE_CAR',
    name: 'NPF Patrol Vehicle',
    slogan: 'To Serve And Protect',
    heat: 5,
    fuelPercent: 100,
    doorState: 'CLOSED',
    passengers: [],
    upgrades: {
      loudHorn: false,
      musicalHorn: false,
      ledLights: false,
      leatherSeats: false,
      soundSystem: false,
      engineTuning: false,
      tintedWindows: false,
      alloys: false
    }
  },
  ARMY_JEEP: {
    speed: 0,
    maxSpeed: 100,
    acceleration: 5,
    handling: 5,
    durability: 100,
    capacity: 14,
    condition: 100,
    mileage: 0,
    color: '#ffcc00',
    id: 'ARMY_JEEP',
    name: 'KIA KM420 Jeep',
    slogan: 'Clear Road',
    heat: 5,
    fuelPercent: 100,
    doorState: 'CLOSED',
    passengers: [],
    upgrades: {
      loudHorn: false,
      musicalHorn: false,
      ledLights: false,
      leatherSeats: false,
      soundSystem: false,
      engineTuning: false,
      tintedWindows: false,
      alloys: false
    }
  },
  TOYOTA_TOWNACE: {
    speed: 0,
    maxSpeed: 100,
    acceleration: 5,
    handling: 5,
    durability: 100,
    capacity: 14,
    condition: 100,
    mileage: 0,
    color: '#ffcc00',
    id: 'TOYOTA_TOWNACE',
    name: 'Toyota Townace',
    slogan: 'Hustle Hard',
    heat: 20,
    fuelPercent: 100,
    doorState: 'CLOSED',
    passengers: [],
    upgrades: {
      loudHorn: false,
      musicalHorn: false,
      ledLights: false,
      leatherSeats: false,
      soundSystem: false,
      engineTuning: false,
      tintedWindows: false,
      alloys: false
    }
  }
};

export const DEFAULT_JUNCTIONS = [
  {
    id: 'j-1',
    name: 'Ikeja Along Bus Stop',
    landmark: 'Under Pedestrian Bridge & Rail Line',
    distanceMarkerMeters: 280,
    waitingPassengersCount: 4,
    averageFare: 500,
    destinationTag: 'Ikeja Along' as const,
    stopReached: false,
    cleared: false,
  },
  {
    id: 'j-2',
    name: 'Maryland Junction',
    landmark: 'Maryland Mall & Bank Clustered Bay',
    distanceMarkerMeters: 750,
    waitingPassengersCount: 5,
    averageFare: 600,
    destinationTag: 'Third Mainland Bridge / Obalende' as const,
    stopReached: false,
    cleared: false,
  },
  {
    id: 'j-3',
    name: 'Anthony Interchange',
    landmark: 'Expressway Flyover Ramp & BRT Lane',
    distanceMarkerMeters: 1250,
    waitingPassengersCount: 4,
    averageFare: 700,
    destinationTag: 'Oshodi Interchange' as const,
    stopReached: false,
    cleared: false,
  },
  {
    id: 'j-4',
    name: 'Oshodi Underbridge Terminal',
    landmark: 'Massive Interchange, Hustlers & Market Women',
    distanceMarkerMeters: 1800,
    waitingPassengersCount: 6,
    averageFare: 800,
    destinationTag: 'Ojuelegba Underbridge' as const,
    stopReached: false,
    cleared: false,
  },
  {
    id: 'j-5',
    name: 'Ojuelegba Flyover',
    landmark: 'Iconic Afrobeat Overpass & Street Bukka',
    distanceMarkerMeters: 2350,
    waitingPassengersCount: 5,
    averageFare: 900,
    destinationTag: 'Lekki Phase 1 Toll Gate' as const,
    stopReached: false,
    cleared: false,
  },
  {
    id: 'j-6',
    name: 'CMS Marina Terminal',
    landmark: 'Waterfront Lagoon Jetty & Financial Towers',
    distanceMarkerMeters: 3000,
    waitingPassengersCount: 7,
    averageFare: 1200,
    destinationTag: 'CMS Marina Terminal' as const,
    stopReached: false,
    cleared: false,
  },
];

export const CONDUCTOR_ROSTER = [
  {
    id: 'rasaki',
    name: 'Rasaki Catch-It',
    nickname: 'Agbero Pro',
    dailyFee: 1500,
    speedMultiplier: 1.5,
    shoutBonus: 2,
    description: 'Master of the passenger folding door. Claps bus side (GBAM-GBAM!) and pulls passengers inside in seconds.',
  },
  {
    id: 'baba-epe',
    name: 'Baba Epe',
    nickname: 'Park Veteran',
    dailyFee: 2500,
    speedMultiplier: 1.8,
    shoutBonus: 3,
    description: 'Commands respect from LASTMA officers and street touts. Increases fare payouts and settles disputes automatically.',
  },
  {
    id: 'segun-wire',
    name: 'Segun Wire',
    nickname: 'Lightning Hustler',
    dailyFee: 2000,
    speedMultiplier: 2.2,
    shoutBonus: 2,
    description: 'Fastest money changer in Lagos. Instantly resolves big bill disputes and loads bus stops in record time.',
  },
];

export const MISSIONS_CATALOG = [
  {
    id: 'mission-1',
    title: 'VIP Park-Out',
    location: 'Balogun Market Tight Alley',
    description: 'Reverse out of a tight parking slot in Balogun Market without touching surrounding cars or market stalls.',
    timeLimitSec: 60,
    targetDistanceMeters: 600,
    rewardNaira: 15000,
    badge: 'Precision Parking Badge',
    type: 'PARK_OUT' as const,
  },
  {
    id: 'mission-2',
    title: 'Lane Discipline Run',
    location: 'Third Mainland Bridge Expressway',
    description: 'Drive 2,000m down the expressway maintaining smooth speed, avoiding potholes, and staying inside lane dividers.',
    timeLimitSec: 90,
    targetDistanceMeters: 2000,
    rewardNaira: 18000,
    badge: 'Expressway Pilot',
    type: 'LANE_DISCIPLINE' as const,
  },
  {
    id: 'mission-3',
    title: 'Smooth Stop Challenge',
    location: 'Oshodi Bus Interchange',
    description: 'Pick up commuters and brake gently into the yellow bus stop bays. Keep the passenger Comfort Meter green (>80%).',
    timeLimitSec: 80,
    targetDistanceMeters: 1400,
    rewardNaira: 16500,
    badge: 'Comfort Chauffeur',
    type: 'SMOOTH_STOP' as const,
  },
  {
    id: 'mission-4',
    title: 'Fuel Saver Coasting',
    location: 'Ojuelegba Flyover Incline',
    description: 'Reach the destination with limited fuel reserves. Shift into Neutral [N] to coast and minimize hard braking.',
    timeLimitSec: 75,
    targetDistanceMeters: 1800,
    rewardNaira: 20000,
    badge: 'Master Economizer',
    type: 'FUEL_SAVER' as const,
  },
  {
    id: 'mission-5',
    title: 'Narrow Squeeze',
    location: 'Computer Village Otigba Street',
    description: 'Thread the Danfo through congested market stalls with illegally parked okadas on both sides without scratching mirrors.',
    timeLimitSec: 70,
    targetDistanceMeters: 1200,
    rewardNaira: 22000,
    badge: 'Alleyway Surgeon',
    type: 'NARROW_SQUEEZE' as const,
  },
];

export interface UpgradeCatalogItem {
  id: keyof Bus['upgrades'];
  name: string;
  costNaira: number;
  description: string;
  benefit: string;
  icon: string;
  visualCue: string;
}

export const UPGRADE_CATALOG: UpgradeCatalogItem[] = [
  {
    id: 'dualRadiatorFan',
    name: 'Dual Electric Radiator Fan',
    costNaira: 3500,
    description: 'High-velocity auxiliary cooling fan wired directly to the battery.',
    benefit: '+50% Engine Heat Dissipation (prevents boiling in traffic)',
    icon: '❄️',
    visualCue: 'Front radiator intake grill & cool blue engine aura',
  },
  {
    id: 'heavyBullBar',
    name: 'Reinforced Steel Bull-Bar',
    costNaira: 4500,
    description: 'Welded tubular steel front armor bumper built for rough Lagos driving.',
    benefit: '-60% Durability damage on collisions & barrier scrapes',
    icon: '🛡️',
    visualCue: 'Heavy chrome & black front cowcatcher bumper bar',
  },
  {
    id: 'roofMegaSpeakers',
    name: 'High-Watt Roof Mega-Speakers',
    costNaira: 4000,
    description: 'Double 500W horn speakers bolted directly to the luggage rack.',
    benefit: '+30% Passenger patience & drowns out herbal preachers',
    icon: '📢',
    visualCue: 'Dual rooftop megaphones with animated sound vibrations',
  },
  {
    id: 'musicalHorn',
    name: '3-Tone Melodic Air Horn',
    costNaira: 2800,
    description: 'Electric trumpet horn playing syncopated street fanfare.',
    benefit: 'Clears okadas & slow traffic 2x faster with maximum style',
    icon: '🎺',
    visualCue: 'Gold trumpet horn mounted above driver cabin',
  },
  {
    id: 'offroadSuspension',
    name: 'Heavy-Duty Shock Dampers',
    costNaira: 4200,
    description: 'Reinforced coil springs and hydraulic shock absorbers for Oshodi craters.',
    benefit: '-50% Pothole impact shock & zero tire blowout penalty',
    icon: '🛞',
    visualCue: 'High-clearance rally wheel arches & mud flaps',
  },
  {
    id: 'customUnderglow',
    name: 'Lagos Neon Underglow',
    costNaira: 3200,
    description: 'High-intensity yellow & emerald street neon illuminating the asphalt.',
    benefit: '+20% Hustle meter generation & Street Cred multiplier',
    icon: '✨',
    visualCue: 'Vibrant neon ground reflection pulsing beneath chassis',
  },
];

export const SHIFT_CONFIGS: Record<ShiftTimeOfDay, ShiftConfig> = {
  MORNING_RUSH: {
    id: 'MORNING_RUSH',
    title: 'Morning Rush Hour',
    subtitle: 'Third Mainland Bottleneck & High Passenger Demand',
    startTime: '06:00 AM',
    endTime: '10:00 AM',
    durationSeconds: 90, // Fast-paced 90 seconds shift
    baseTrafficDensity: 0.7,
    potholeFrequency: 0.4,
    floodRisk: false,
    policePresence: 0.3,
    passengerMultiplier: 1.5,
    unionLevy: 3500, // Chairman demands ₦3,500
  },
  MIDDAY_HUSTLE: {
    id: 'MIDDAY_HUSTLE',
    title: 'Midday Heat & LASTMA Patrols',
    subtitle: 'Blistering Sun, High Overheating Risk & Checkpoints',
    startTime: '10:00 AM',
    endTime: '04:00 PM',
    durationSeconds: 90,
    baseTrafficDensity: 0.5,
    potholeFrequency: 0.5,
    floodRisk: false,
    policePresence: 0.75, // Heavy checkpoints
    passengerMultiplier: 1.0,
    unionLevy: 4000,
  },
  EVENING_RUSH: {
    id: 'EVENING_RUSH',
    title: 'Evening Rush & Flash Floods',
    subtitle: 'Torrential Rain, High Fares & Reckless Rival Danfos',
    startTime: '04:00 PM',
    endTime: '10:00 PM',
    durationSeconds: 105,
    baseTrafficDensity: 0.85,
    potholeFrequency: 0.7,
    floodRisk: true,
    policePresence: 0.4,
    passengerMultiplier: 2.2, // Huge fares
    unionLevy: 5000,
  },
};

export const DESTINATIONS: LagosDestination[] = [
  'Oshodi Interchange',
  'Ikeja Along',
  'Third Mainland Bridge / Obalende',
  'Ojuelegba Underbridge',
  'Lekki Phase 1 Toll Gate',
  'CMS Marina Terminal',
];

export const PASSENGER_NAMES = [
  'Babatunde', 'Chidi', 'Nkechi', 'Funke', 'Emeka', 
  'Adeola', 'Yemi', 'Ifeanyi', 'Kemi', 'Oluwaseun',
  'Blessing', 'Tari', 'Folake', 'Kunle', 'Seyi'
];

export const SLOGANS = [
  'No King as God',
  'Face Your Front',
  'Work and Pray',
  'No Condition Is Permanent',
  'Back to Sender',
  'Destiny Cannot Be Changed',
  'Eko Oni Baje'
];

export const DEFAULT_HOUSE = {
  id: 'FACE_ME_I_SLAP_YOU' as const,
  title: 'Face-Me-I-Face-You Single Room',
  location: 'Olosa Street, Mushin, Lagos',
  rentCost: 8000, // Weekly rent
  purchaseCost: 0,
  isOwned: false,
  hasGenerator: false,
  generatorFuelLiters: 0,
  nepaActive: false, // NEPA blackout at start!
  hasStove: true,
  description: 'Humble single room in a crowded compound. Shared bathroom, ceiling fan, and noisy street neighbors. Must pay landlord rent and NEPA bills!',
  comfortRating: 25,
};

export const HOUSE_TIERS = [
  {
    id: 'FACE_ME_I_SLAP_YOU' as const,
    title: 'Face-Me-I-Face-You Single Room',
    location: 'Olosa Street, Mushin',
    rentCost: 8000,
    purchaseCost: 0,
    hasGenerator: false,
    hasStove: true,
    comfortRating: 25,
    description: 'Classic starter room. Shared kitchen hallway. NEPA light cuts frequently.',
  },
  {
    id: 'SELF_CONTAIN' as const,
    title: 'Self-Contain Room & Parlour',
    location: 'Ogunlana Drive, Surulere',
    rentCost: 35000,
    purchaseCost: 120000,
    hasGenerator: true,
    hasStove: true,
    comfortRating: 60,
    description: 'Private bathroom, fenced gate, and your own "I-Better-Pass-My-Neighbor" generator set!',
  },
  {
    id: 'FLAT_3BED' as const,
    title: 'Modern 3-Bedroom Flat',
    location: 'Medina Estate, Gbagada',
    rentCost: 75000,
    purchaseCost: 280000,
    hasGenerator: true,
    hasStove: true,
    comfortRating: 85,
    description: 'Serene gated estate, prepaid electric meter, solar inverter backup, and tiled compound.',
  },
  {
    id: 'LEKKI_DUPLEX' as const,
    title: 'Luxury 5-Bedroom Waterfront Duplex',
    location: 'Admiralty Way, Lekki Phase 1',
    rentCost: 180000,
    purchaseCost: 750000,
    hasGenerator: true,
    hasStove: true,
    comfortRating: 100,
    description: 'The Lagos Big Boy dream! Private swimming pool, 24/7 uninterrupted power, ocean breeze!',
  },
];

export const DEFAULT_INVENTORY = [
  {
    id: 'item-indomie',
    name: 'Carton of Indomie Noodles',
    category: 'GROCERY' as const,
    quantity: 6,
    icon: '🍜',
    description: 'Super pack onion flavor. Cook at home on the stove for instant energy!',
    effect: '+35 Stamina when cooked',
  },
  {
    id: 'item-eggs',
    name: 'Farm Fresh Eggs',
    category: 'GROCERY' as const,
    quantity: 8,
    icon: '🥚',
    description: 'Fried eggs to pair with noodles or yam.',
    effect: '+20 Stamina',
  },
  {
    id: 'item-yam',
    name: 'Tuber of Abuja Yam',
    category: 'GROCERY' as const,
    quantity: 2,
    icon: '🍠',
    description: 'Boil or fry with egg sauce for a heavy driver meal.',
    effect: '+50 Stamina',
  },
  {
    id: 'item-coolant',
    name: 'Radiator Anti-Freeze Coolant',
    category: 'SPARE_PART' as const,
    quantity: 2,
    icon: '❄️',
    description: 'Pour into radiator during heavy traffic to drop temperature by 40°C.',
    effect: '-40°C Engine Heat',
  },
  {
    id: 'item-sunglasses',
    name: 'Ray-Ban Aviator Shades',
    category: 'GEAR' as const,
    quantity: 1,
    icon: '🕶️',
    description: 'Driver swag on Third Mainland Bridge. Passengers tip +10% extra!',
    effect: '+10% Fare Tips',
  },
];

export const DEFAULT_MESSAGES = [
  {
    id: 'msg-landlord',
    sender: 'Landlord Baba Alagbo',
    avatar: '👴🏾',
    preview: 'Mr. Rasaki, your Mushin room rent ₦8,000 is due today!',
    fullText: 'Mr. Rasaki, your weekly room rent of ₦8,000 is overdue! If you do not pay by 6:00 PM today, I will padlock the room door and give it to another tenant! Use your phone Bank app to transfer the money immediately!',
    timestamp: '11:42 AM',
    unread: true,
    actionRequired: 'PAY_RENT' as const,
    costNaira: 8000,
  },
  {
    id: 'msg-nepa',
    sender: 'EKEDC / NEPA Power',
    avatar: '⚡',
    preview: 'DISCONNECTION NOTICE: Outstanding ₦4,500 electricity bill.',
    fullText: 'Dear Customer, your compound has an outstanding power bill of ₦4,500. NEPA technicians are already on your street with ladders. Pay immediately via mobile banking to avoid wire cutting!',
    timestamp: '10:15 AM',
    unread: true,
    actionRequired: 'PAY_NEPA' as const,
    costNaira: 4500,
  },
  {
    id: 'msg-wife',
    sender: 'Iya Junior (Wife)',
    avatar: '👩🏾',
    preview: 'Remember to bring cooking oil and Indomie home o!',
    fullText: 'Bamidele, as you are returning from park this evening, stop at the roadside market and buy cooking oil and bread. Junior is also crying for gala. Drive safely o!',
    timestamp: '09:30 AM',
    unread: false,
  },
  {
    id: 'msg-chairman',
    sender: 'Alhaji Park Chairman',
    avatar: '🧔🏾',
    preview: 'Park Union tickets are ₦3,500 today.',
    fullText: 'All Danfo drivers operating on Third Mainland corridor must remit their daily ₦3,500 union levy before 5:00 PM. No rough play with agbero boys at checkpoints!',
    timestamp: '07:00 AM',
    unread: false,
    actionRequired: 'PAY_LEVY' as const,
    costNaira: 3500,
  },
];

export const CHOWDECK_MENU = [
  {
    id: 'food-jollof',
    name: 'Party Jollof Rice & Fried Plantain (Dodo)',
    price: 2800,
    icon: '🍛',
    restaurant: 'The Place / Bukka Express',
    description: 'Smokey party firewood jollof with two pieces of fried beef and sweet dodo.',
    staminaGain: 55,
  },
  {
    id: 'food-suya',
    name: 'Mega Beef Suya & Roasted Pepper',
    price: 2200,
    icon: '🥩',
    restaurant: 'Glover Court Suya',
    description: 'Charcoal grilled spicy suya with sliced onions, cabbage and extra yaji pepper.',
    staminaGain: 40,
  },
  {
    id: 'food-amala',
    name: 'Hot Amala, Gbegiri, Ewedu & Goat Meat',
    price: 3600,
    icon: '🍲',
    restaurant: 'White House Bukka Yaba',
    description: 'Silky black amala with assorted goat meat and fresh palm oil stew. Heavy driver fuel!',
    staminaGain: 80,
  },
  {
    id: 'food-malt-pie',
    name: 'Chilled Malta Guinness & Spicy Meat Pie',
    price: 1500,
    icon: '🥧',
    restaurant: 'Mega Chicken Bakery',
    description: 'Ice cold malt drink and fresh buttery minced beef pie.',
    staminaGain: 30,
  },
];

export const DEFAULT_GAS_STATIONS = [
  {
    id: 'gas-1',
    name: 'Total Energies Express Plaza',
    brand: 'TOTAL',
    distanceMarkerMeters: 520,
    fuelPricePerLiter: 950,
    isInBay: false,
  },
  {
    id: 'gas-2',
    name: 'Oando Mega Petrol Station',
    brand: 'OANDO',
    distanceMarkerMeters: 1750,
    fuelPricePerLiter: 920,
    isInBay: false,
  },
];

export const DEFAULT_ROADSIDE_SHOPS = [
  {
    id: 'shop-ikeja',
    name: 'Computer Village Tech Hub',
    locationName: 'Ikeja Along Bus Stop',
    distanceMarkerMeters: 310,
    category: 'TECH' as const,
    items: [
      { id: 'item-charger', name: 'Fast Car Phone Charger', price: 2500, icon: '🔌', description: 'Keeps driver phone charged at 100%', category: 'GEAR' as const },
      { id: 'item-airpods', name: 'Wireless Bluetooth Earpiece', price: 6500, icon: '🎧', description: 'Take calls hands-free while driving', category: 'GEAR' as const },
      { id: 'item-shades', name: 'Ray-Ban Aviator Shades', price: 4000, icon: '🕶️', description: 'Passenger respect +10%', category: 'GEAR' as const },
    ],
  },
  {
    id: 'shop-maryland',
    name: 'Maryland Mall Food & Market',
    locationName: 'Maryland Junction',
    distanceMarkerMeters: 780,
    category: 'FOOD' as const,
    items: [
      { id: 'item-indomie-shop', name: 'Carton of Indomie Noodles', price: 7500, icon: '🍜', description: 'Cook at home on stove', category: 'GROCERY' as const },
      { id: 'item-eggs-shop', name: 'Crate of Eggs (30 pcs)', price: 3800, icon: '🥚', description: 'Fresh farm eggs', category: 'GROCERY' as const },
      { id: 'item-energy-drink', name: 'Fearless Energy Drink (Cold)', price: 600, icon: '⚡', description: 'Restores instant focus & stamina', category: 'MEAL' as const },
    ],
  },
  {
    id: 'shop-anthony',
    name: 'Express Auto Parts & Spares',
    locationName: 'Anthony Interchange',
    distanceMarkerMeters: 1280,
    category: 'AUTO_PARTS' as const,
    items: [
      { id: 'item-coolant-shop', name: 'Heavy Radiator Coolant', price: 2800, icon: '❄️', description: 'Cools engine by 40°C', category: 'SPARE_PART' as const },
      { id: 'item-spark-plugs', name: 'Bosch Spark Plugs Set', price: 4500, icon: '⚙️', description: '+15% acceleration boost', category: 'SPARE_PART' as const },
      { id: 'item-brake-fluid', name: 'DOT 4 Hydraulic Brake Fluid', price: 3200, icon: '🛑', description: 'Restores 100% brake stopping power', category: 'SPARE_PART' as const },
    ],
  },
  {
    id: 'shop-oshodi',
    name: 'Oshodi Central Market & Bukka',
    locationName: 'Oshodi Underbridge',
    distanceMarkerMeters: 1840,
    category: 'GROCERY' as const,
    items: [
      { id: 'item-yam-shop', name: 'Tuber of Abuja Yam', price: 2500, icon: '🍠', description: 'Heavy staple food', category: 'GROCERY' as const },
      { id: 'item-plantain', name: 'Bunch of Ripe Plantain (Dodo)', price: 1800, icon: '🍌', description: 'Fry at home with eggs', category: 'GROCERY' as const },
      { id: 'item-pure-water', name: 'Bag of Chilled Pure Water (20 sachets)', price: 500, icon: '💧', description: 'Radiator emergency water', category: 'GROCERY' as const },
    ],
  },
];

